
server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:latest
          temperature: 0.7
  application:
    name: CareerUp
  datasource:
    password: ${DBPASSWORD:}
    url: ${DBURL:jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL}
    username: ${DBUSER:}
    driver-class-name: ${DBDRIVER:oracle.jdbc.driver.OracleDriver}
  mail:
    host: ${MAILHOST:smtp.gmail.com}
    port: 587
    username: ${MAILUSER:}
    password: ${MAILPASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    addresses: ${RABBITADRESS:}
    queue: ${RABBITQUEUE:}
  jpa:

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DBDIALECT:org.hibernate.dialect.OracleDialect}
        format_sql: true
    show-sql: true
